root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  delay = 1000
  exclude_dir = ["assets", "vendor", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html", "sql"]
  exclude_regex = [".*_test.go"]

[log]
  main_only = true

[misc]
  clean_on_exit = true
