-- +goose Up

INSERT INTO categories (name, slug) VALUES
  ('Светильники', 'lamps'),
  ('Ночники', 'nightlights')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;

DELETE FROM products WHERE slug <> 'arkane';

INSERT INTO content (component, data) VALUES
('hero', $json${"badge":"О SPARROW","title":"Рождённый слой за слоем","subtitle":"Уникальные светильники из 3D-печати","cta_primary":{"text":"СМОТРЕТЬ МОДЕЛИ","link":"/catalog"},"cta_secondary":{"text":"КАК МЫ ДЕЛАЕМ","link":"/process"},"image_url":"/content/home/hero.jpg"}$json$::jsonb),
('ticker', $json${"items":["✦ 3D-ПЕЧАТЬ","✦ РУЧНАЯ РАБОТА","✦ УНИКАЛЬНЫЙ СВЕТ","✦ SPARROW","✦ ЖИВЫЕ ТЕНИ","✦ КАСТОМНЫЙ ЗАКАЗ","✦ ЭКОЛОГИЧНО","✦ СДЕЛАНО В РОССИИ"]}$json$::jsonb),
('about', $json${"label":"О SPARROW","title":"Свет как искусство","description":"Каждый светильник Sparrow — ручная работа. Никаких штампов, никаких повторов.","tags":["Воробей — везде","Только 3D-печать","Любой цвет","PLA-пластик"],"image_url":"/content/about/pic.jpg"}$json$::jsonb),
('materials', $json${"label":"МАТЕРИАЛЫ","title":"Из чего мы строим свет","materials":[{"name":"PLA","full_name":"Полимолочная кислота","description":"Биоразлагаемый, 14 цветов","color":"#00c45a","tags":["Био","14 цв","Мат"]},{"name":"PETG","full_name":"Полиэтилентерефталат","description":"Прочный, полупрозрачный","color":"#7b61ff","tags":["Прозр","Проч","8 цв"]},{"name":"ASA","full_name":"Акрилонитрил-стирол-акрилат","description":"УФ-стойкий, для улицы","color":"#ff4d00","tags":["УФ","Влага","6 цв"]},{"name":"TPU","full_name":"Термопластичный полиуретан","description":"Гибкий, тактильный","color":"#ffd600","tags":["Гибк","Мягк","Натур"]}]}$json$::jsonb),
('reviews', $json${"label":"ОТЗЫВЫ","title":"Говорят","rating":4.9,"review_count":143,"reviews":[{"id":1,"name":"Алина К.","city":"Москва","text":"Тени на стенах потрясающие. Все гости спрашивают, где взяла.","color":"#ff4d00"},{"id":2,"name":"Дмитрий Р.","city":"Санкт-Петербург","text":"Сделали под наш фирменный цвет — результат стоит того.","color":"#7b61ff"},{"id":3,"name":"Маша Ю.","city":"Казань","text":"Идеальный подарок. Это по-настоящему уникально и не как у всех.","color":"#58cc02"},{"id":4,"name":"Игорь С.","city":"Екатеринбург","text":"Хороший светильник, экологичный материал. Качеством доволен.","color":"#ffd600"}]}$json$::jsonb),
('faq', $json${"label":"FAQ","title":"Вопросы?","items":[{"question":"Сколько времени?","answer":"Среднее время изготовления — от 3 до 7 рабочих дней в зависимости от сложности модели."},{"question":"Нестандартный цвет?","answer":"Мы можем подобрать цвет по вашему образцу. Доступно более 50 оттенков PLA-пластика."},{"question":"Насколько прочные?","answer":"Светильники из PLA и PETG достаточно прочны для повседневного использования. ASA подходит для улицы."},{"question":"Доставка?","answer":"Отправляем по всей России СДЭКом и Почтой России. Стоимость зависит от региона."},{"question":"Гарантия?","answer":"Мы даём гарантию 6 месяцев на все светильники. При производственном браке заменим изделие."},{"question":"Какая лампочка?","answer":"Подходит стандартная лампочка с цоколем E27. Рекомендуем LED-лампы — они не нагревают пластик."}]}$json$::jsonb),
('footer', $json${"logo_text":"SPARROW","description":"3D-printed designer lamps. Каждый светильник — ручная работа.","social":[{"name":"Telegram","url":"#"},{"name":"VK","url":"#"},{"name":"WhatsApp","url":"#"}],"nav":[{"title":"Навигация","links":[{"text":"О нас","url":"/about"},{"text":"Модели","url":"/catalog"},{"text":"Процесс","url":"/process"},{"text":"Цифровые продукты","url":"/digital-catalog"},{"text":"Новости","url":"#"}]},{"title":"Контакты","links":[{"text":"hello@sparrow.studio","url":"mailto:hello@sparrow.studio"},{"text":"Москва, Россия","url":"#"}]},{"title":"Информация","links":[{"text":"Политика конфиденциальности","url":"#"},{"text":"Условия использования","url":"#"}]}],"copyright":"© 2024 Sparrow"}$json$::jsonb),
('catalog_page', $json${"breadcrumbs":[{"label":"Главная","to":"/"},{"label":"Каталог","to":"/catalog"}],"page_title":"Каталог","empty_state":"Нет товаров в этой категории"}$json$::jsonb),
('catalog_cta', $json${"heading":"Твой свет уже ждёт","description":"Оставь заявку — обсудим размер, цвет и материал. Первая консультация бесплатно.","button_text":"Создать свой","button_link":"/constructor"}$json$::jsonb),
('product_hero_section', $json${"price_label":"Ориентировочная стоимость","buttons":{"order":"ОФОРМИТЬ ПРЕДЗАКАЗ","similar":"СДЕЛАТЬ ПОХОЖИЙ"},"loading":"Загрузка...","not_found":"Товар не найден"}$json$::jsonb),
('product_specs_section', $json${"badge":"ХАРАКТЕРИСТИКИ","heading":"Технические данные"}$json$::jsonb),
('product_box_section', $json${"badge":"КОМПЛЕКТАЦИЯ","heading":"В коробке"}$json$::jsonb),
('product_story_section', $json${"badge":"ОБ ИЗДЕЛИИ","heading":"История модели"}$json$::jsonb),
('about_hero', $json${"label":"О МАСТЕРСКОЙ","title":"Свет из рук, а не с конвейера","description":"Sparrow — это не фабрика. Это уютная домашняя мастерская, где 3D-принтеры работают, пока мы спим, а каждое изделие проходит через ручную шлифовку, сборку и тест."}$json$::jsonb),
('about_values', $json${"label":"ЦЕННОСТИ","values":[{"title":"Честность","description":"Говорим правду о сроках и стоимости. Если что‑то идёт не так — сообщаем сразу.","color":"#ff4d00"},{"title":"Качество","description":"Не выпускаем изделие, пока не убедимся, что оно идеально. Тестируем 24 часа.","color":"#58cc02"},{"title":"Уникальность","description":"Никаких серийных тиражей. Каждый светильник — единственный в своём роде.","color":"#7b61ff"},{"title":"Диалог","description":"Слушаем клиента на каждом этапе. Ваше мнение важнее нашего.","color":"#ffd600"}]}$json$::jsonb),
('about_author', $json${"label":"АВТОР ПРОЕКТА","name":"Олег Хайцын","role":"Основатель и мастер","image_url":"/content/about/me.jpg","bio":["Sparrow родился из простого желания — создавать вещи, которых нет ни у кого. Всё началось с одного 3D-принтера на кухне и интереса к тому, как свет меняет пространство. Первый светильник сделал для себя, второй — по просьбе друга, а к третьему выстроилась очередь.","Сегодня Sparrow — это не про бизнес. Это про возможность делать то, что любишь, и видеть, как твоя работа освещает чей‑то дом. Каждое изделие проходит через мои руки: от эскиза до финальной шлифовки. Потому что по-другому я не умею."],"social":[{"name":"TG","url":"#"},{"name":"WA","url":"#"}]}$json$::jsonb),
('about_atmosphere', $json${"label":"АТМОСФЕРА","title":"Как устроен Sparrow","image_url":"/content/about/lab.jpg","description":["В мастерской пахнет пластиком и кофе. За окном — воробьи, вдохновляющие названием студии. Три принтера печатают детали, на столе — эскизы следующей модели. Каждый светильник начинается с разговора: «Что вам нужно? Какой свет вы любите?»","Мы не работаем на склад. Каждый заказ — это диалог. Мы делаем мало, но тщательно. Иногда на одну модель уходит неделя — и это нормально, потому что результат стоит того."]}$json$::jsonb),
('about_contacts', $json${"label":"КОНТАКТЫ","title":"Свяжитесь с нами","contacts":[{"label":"Email","value":"hello@sparrow.studio"},{"label":"Telegram","value":"@sparrow_studio"},{"label":"ВКонтакте","value":"vk.com/sparrowstudio"}],"cta":{"text":"НАПИСАТЬ","link":"mailto:hello@sparrow.studio"}}$json$::jsonb),
('process_hero', $json${"label":"8 ЭТАПОВ","title":"Процесс создания","description":"От 3D-модели до готового устройства. Каждый светильник проходит 8 этапов — с ручной обработкой и контролем качества."}$json$::jsonb),
('process_arsenal', $json${"label":"НАШ АРСЕНАЛ","title":"Оборудование и инструменты","items":[{"title":"Prusa MK4","description":"Флагманский FDM-принтер с автокалибровкой и мульти-материальным блоком","color":"#ff4d00"},{"title":"Bambu Lab X1C","description":"Скоростная система с AMS — печать 16 цветов одновременно","color":"#58cc02"},{"title":"Prusa SL1S","description":"Фотополимерный принтер для сверхточных мелких деталей","color":"#7b61ff"},{"title":"Dremel 8260","description":"Профессиональный гравёр для постобработки и финишной шлифовки","color":"#ffd600"},{"title":"Аэрограф Iwata","description":"Японский аэрограф для нанесения покрытий и декоративной покраски","color":"#ff4d00"},{"title":"Muse Core","description":"CO₂-лазер для гравировки и точной резки акрила и деталей","color":"#58cc02"}]}$json$::jsonb),
('process_stages', $json${"stages":[{"title":"Идея и дизайн","duration":"⏱ 1–2 дня","description":"Всё начинается с разговора. Мы слушаем, задаём вопросы и погружаемся в контекст — интерьер, настроение, функцию. Идея кристаллизуется в серии эскизов и концепций.","color":"#ff4d00","icon_bg":"dark","tags":["Консультация","Брифинг","Эскизы"]},{"title":"3D-моделирование","duration":"⏱ 2–4 дня","description":"Переводим эскизы в трёхмерную модель. Прорабатываем пропорции, эргономику и распределение света. Создаём фотореалистичные рендеры для согласования с заказчиком.","color":"#58cc02","icon_bg":"dark","tags":["Fusion 360","Blender","KeyShot"]},{"title":"Подготовка к печати","duration":"⏱ 3–6 часов","description":"Разбиваем модель на слои для принтера. Настраиваем поддержки, заполнение, скорость и температуру для оптимального результата. Выбираем материал и цвет.","color":"#7b61ff","icon_bg":"white","tags":["PrusaSlicer","Cura","Настройки"]},{"title":"3D-печать","duration":"⏱ 8–24 часа","description":"Запускаем принтер и наблюдаем за процессом. Каждые несколько часов проверяем качество слоёв. Один корпус печатается от 8 до 24 часов в зависимости от сложности.","color":"#ff4d00","icon_bg":"dark","tags":["Мониторинг"]},{"title":"Финишинг","duration":"⏱ 4–8 часов","description":"Удаляем поддержки, шлифуем поверхность, склеиваем детали. При необходимости наносим краску или покрытие. Каждый шов обрабатывается вручную.","color":"#58cc02","icon_bg":"dark","tags":["Шлифовка","Склейка","Покраска"]},{"title":"Электроника","duration":"⏱ 2–4 часа","description":"Монтируем LED-модуль, контроллер ESP32 и проводку. Настраиваем Wi-Fi соединение с AIR-платформой. Каждое соединение проверяется мультиметром.","color":"#7b61ff","icon_bg":"white","tags":["LED модуль","ESP32","Wi‑Fi"]},{"title":"Тестирование","duration":"⏱ 24 часа","description":"Проверяем все режимы работы: яркость, цвет, сценарии управления. Оставляем под нагрузкой на 24 часа. Документируем результаты и делаем финальные фото.","color":"#ff4d00","icon_bg":"dark","tags":["Тест нагрузки","Мультиметр","Фотофиксация"]},{"title":"Упаковка","duration":"⏱ 1 час","description":"Упаковываем в фирменную коробку с поролоновыми вставками. Вкладываем инструкцию, гарантийный талон и небольшой сюрприз. Готовим к отправке.","color":"#58cc02","icon_bg":"dark","tags":["Фирменная коробка","Поролон","Документы"]}]}$json$::jsonb),
('process_cta', $json${"title":"Твой свет уже ждёт","description":"Оставь заявку — обсудим размер, цвет и материал. Создадим именно то, что ты представляешь.","button_text":"Создать свой","button_link":"/constructor"}$json$::jsonb),
('digital_catalog_page', $json${"breadcrumbs":[{"label":"Главная","to":"/"},{"label":"Цифровые продукты","to":"/digital-catalog"}],"hero":{"badge":"ЦИФРОВЫЕ ПРОДУКТЫ","heading":"Open-source инфраструктура","description":"Sparrow разрабатывает не только светильники. Наши цифровые продукты — открытые, модульные и готовые к использованию."},"button_text":"ПОДРОБНЕЕ →"}$json$::jsonb),
('digital_features_section', $json${"badge":"ВОЗМОЖНОСТИ"}$json$::jsonb),
('digital_architecture_section', $json${"badge":"КАК ЭТО РАБОТАЕТ","heading":"Архитектура системы"}$json$::jsonb),
('digital_techstack_section', $json${"badge":"ТЕХНОЛОГИИ","heading":"Стек"}$json$::jsonb),
('digital_opensource_section', $json${"heading":"Открытый код","button_text":"НА GITHUB"}$json$::jsonb)
ON CONFLICT (component) DO UPDATE
SET data = EXCLUDED.data,
    updated_at = now();

INSERT INTO products (name, name_ru, slug, description, price, image_url, badge, colors, bg_color, category_id, in_stock, details)
VALUES (
  'Arkane',
  'Аркейн',
  'arkane',
  'Группа лёгких форм, парящих в пространстве. Arkane создаёт композицию из нескольких абажуров, напоминающую птичью стаю в полёте.',
  7800,
  '/content/catalog-item/arkane-1.jpg',
  'ТОЛЬКО ПО ПРЕДЗАКАЗУ',
  '["#ff4d00","#ffd600","#58cc02","#7b61ff","#1a1a1a"]'::jsonb,
  '#f0edff',
  (SELECT id FROM categories WHERE slug = 'lamps'),
  false,
  $json${"description":"Группа лёгких форм, парящих в пространстве. Arkane создаёт композицию из нескольких абажуров, напоминающую птичью стаю в полёте.","subtitle":"Подвесной светильник","badge_text":"ТОЛЬКО ПО ПРЕДЗАКАЗУ","lead_time":"Срок изготовления: 21–30 рабочих дней","gallery":[{"image_url":"/content/catalog-item/arkane-1.jpg","bg_color":"#f0edff"},{"image_url":"/content/catalog-item/arkane-2.jpg","bg_color":"#fff0eb"}],"specifications":[{"label":"Размеры","value":"300 × 300 × 450 мм"},{"label":"Вес","value":"1.2 кг"},{"label":"Материал","value":"PLA-пластик / ABS"},{"label":"Технология печати","value":"FDM 3D-печать"},{"label":"Источник света","value":"LED, 2700K-5000K"},{"label":"Питание","value":"220В"},{"label":"Управление","value":"Пульт / приложение"},{"label":"Гарантия","value":"12 месяцев"}],"box_contents":["Блок питания 12В / 3А — 1 шт.","Крепёжный набор","Инструкция на русском языке","Гарантийный талон","Фирменная упаковка Sparrow"],"story_paragraphs":["Arkane родился из наблюдения за птицами, возвращающимися домой на закате. Каждый модуль — отдельная птица, вместе они создают гармоничную, динамичную композицию.","Мы используем лёгкие, но прочные материалы, позволяющие создавать парящие конструкции. Каждый модуль печатается отдельно и собирается вручную.","Arkane — это не просто светильник, это арт-объект, который меняет восприятие пространства. Идеально подходит для высоких потолков и открытых планировок."]}$json$::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  name_ru = EXCLUDED.name_ru,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  badge = EXCLUDED.badge,
  colors = EXCLUDED.colors,
  bg_color = EXCLUDED.bg_color,
  category_id = EXCLUDED.category_id,
  in_stock = EXCLUDED.in_stock,
  details = EXCLUDED.details,
  updated_at = now();

INSERT INTO digital_products (slug, number, title, subtitle, description, content) VALUES
('air', 1, 'AIR', 'Облачная платформа умного освещения', 'Собственная облачная инфраструктура Sparrow для управления светильниками, сбора аналитики и интеграции с умным домом. Микросервисная архитектура на базе MQTT, WebSocket и JWT.', $json${"hero":{"badge":"AIR система","heading":"AIR","description":"AIR — собственная облачная инфраструктура Sparrow, которая обеспечивает управление светильниками, сбор аналитики и интеграцию с умным домом. Микросервисная архитектура на базе MQTT, WebSocket и JWT.","badge_color":"#58cc02"},"features":[{"icon":"air-security","title":"Безопасность","description":"JWT-аутентификация и шифрование канала. Каждое устройство привязано к вашему аккаунту. Сторонний доступ невозможен."},{"icon":"air-analytics","title":"Аналитика","description":"Статистика использования, графики потребления, история изменений. Понимайте, как используются ваши светильники."},{"icon":"air-integration","title":"Интеграция","description":"Совместимость с умным домом и голосовыми ассистентами. Открытая архитектура для интеграции через API."}],"architecture":{"items":[{"title":"Светильник","subtitle":"ESP32 + LED"},{"title":"MQTT / GraphQL / WSS","subtitle":"Gateway"},{"title":"Приложение","subtitle":"Vue 3 / iOS / Android"}],"description":"Светильник подключается к AIR через MQTT-брокер. Gateway аутентифицирует устройство по JWT и маршрутизирует команды в Domain-сервис. Domain управляет состоянием, шаблонами и правами доступа. Приложение общается с системой через WebSocket или HTTP API."},"open_source":{"description":"AIR — проект с открытым исходным кодом. Вы можете изучить архитектуру, развернуть собственную инфраструктуру или внести свой вклад в развитие платформы.","button_text":"AIR НА GITHUB","github_url":"#"}}$json$::jsonb),
('account', 2, 'Account', 'Сервис аккаунтов и авторизации', 'Самостоятельный AGPL–3.0 сервис аккаунтов, авторизации и профилей. HTTP API, gRPC, Vue SPA, OpenAPI и Swagger UI. Готов к развёртыванию в Docker Compose или Kubernetes.', $json${"hero":{"badge":"Account","heading":"ACCOUNT","description":"Account — самостоятельный AGPL–3.0 сервис для управления учётными записями, аутентификации и профилей. Микросервисная архитектура с HTTP API, gRPC и нейтральным Vue-фронтендом.","badge_color":"#ff4d00"},"features":[{"icon":"account-jwt","title":"JWT-авторизация","description":"Аутентификация на основе JSON Web Token. Поддержка refresh-токенов, кастомизация claims и интеграция с любым фронтендом."},{"icon":"account-api-grpc","title":"HTTP API + gRPC","description":"REST API /api/* со Swagger UI. Сервисный gRPC ProfileService для микросервисной архитектуры."},{"icon":"account-vue","title":"Vue 3 SPA","description":"Нейтральный фронтенд на Vue 3 — подключается к любому бекенду. Кастомизация через API и CSS-переменные."},{"icon":"account-swagger","title":"OpenAPI / Swagger","description":"Полная спецификация API в формате OpenAPI 3. Swagger UI доступен сразу после запуска для тестирования эндпоинтов."},{"icon":"account-docker","title":"Docker Compose","description":"Готовый docker-compose.yml для быстрого запуска. Поддержка PostgreSQL, миграции, генерация ключей одной командой."}],"architecture":{"badge":"АРХИТЕКТУРА","heading":"Как это устроено","items":[{"title":"HTTP API","subtitle":"REST /api/*"},{"title":"gRPC","subtitle":"ProfileService"},{"title":"Frontend","subtitle":"Vue 3"},{"title":"База данных","subtitle":"PostgreSQL"}],"description":"Backend предоставляет HTTP API для клиентов и gRPC ProfileService для внутренних сервисов. Frontend — нейтральная Vue SPA, которая подключается к API через HTTP. База данных PostgreSQL хранит профили, сессии и метаданные. Публичный трафик маршрутизируется через reverse proxy или Kubernetes Ingress."},"tech_stack":{"items":[{"category":"Backend","title":"Kotlin"},{"category":"Frontend","title":"Vue 3"},{"category":"API","title":"REST / gRPC"},{"category":"Auth","title":"JWT"},{"category":"DB","title":"PostgreSQL"},{"category":"Docs","title":"OpenAPI"},{"category":"CI/CD","title":"Trivy + Cosign + SBOM"},{"category":"Deploy","title":"Docker / K8s"}]},"open_source":{"description":"Account — проект с открытым исходным кодом (AGPL–3.0). Вы можете изучить код, развернуть собственный экземпляр, форкнуть или внести вклад.","button_text":"ACCOUNT НА GITHUB","github_url":"#"}}$json$::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  number = EXCLUDED.number,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  description = EXCLUDED.description,
  content = EXCLUDED.content;

INSERT INTO configurator_options (id, options)
VALUES (1, $json${"hero":{"label":"КОНФИГУРАТОР","title":"Создай свой светильник","description":"Опишите идею — мы воплотим её в жизнь. Каждый светильник уникален и создаётся специально для вас."},"product_types":["Настольный светильник","Ночник"],"features":[{"id":"smart","label":"Умная подсветка"},{"id":"rgbic","label":"RGBIC"},{"id":"rgb","label":"RGB"},{"id":"bluetooth","label":"Bluetooth"},{"id":"wifi","label":"Wi‑Fi"},{"id":"battery","label":"Аккумулятор"},{"id":"app","label":"Управление через приложение"},{"id":"usbc","label":"USB Type-C"}],"materials":[{"id":"pla","label":"PLA","fullName":"Полимолочная кислота","color":"#00c45a","tags":["Био","14 цв","Мат"]},{"id":"petg","label":"PETG","fullName":"Полиэтилентерефталат","color":"#7b61ff","tags":["Прозр","8 цв","Проч"]},{"id":"asa","label":"ASA","fullName":"Акрилонитрил-стирол-акрилат","color":"#ff4d00","tags":["УФ","12 цв","Жёст"]}],"colors":["#1a1a1a","#ffffff","#ff4d00","#58cc02","#ffd600","#7b61ff","#00c45a","#ec8383","#96d3e6","#f5f0e8","#c84b00","#3e9e00","#b08d4a","#6b6555","#1a1a2e"],"sections":{"product_type":{"step":"01","title":"Что необходимо изготовить"},"features":{"step":"02","title":"Дополнительные функции"},"material":{"step":"03","title":"Материал корпуса"},"color":{"step":"04","title":"Цвет корпуса","note":"Доступно более 40 цветов. Если нужного оттенка нет — укажите в комментарии."},"dimensions":{"step":"05","title":"Примерные размеры","width_label":"Ширина (мм)","height_label":"Высота (мм)","depth_label":"Глубина (мм)","placeholder":"например, 240","note":"* Размеры являются приблизительными. Точные параметры согласовываются при обсуждении проекта."},"files":{"step":"06","title":"Загрузка файлов","title_text":"Перетащите файлы или нажмите","hint":"Изображения, фото, эскизы, референсы — любые форматы"},"description":{"step":"07","title":"Описание идеи","placeholder":"Опишите максимально подробно: назначение, атмосферу, стиль интерьера, пожелания по свету и форме. Чем подробнее — тем точнее результат."}},"submit":{"disclaimer":"Отправляя заявку, вы оформляете предзаказ, а не покупаете готовый товар. Стоимость и сроки согласовываются индивидуально.","button_text":"ОТПРАВИТЬ ЗАЯВКУ"}}$json$::jsonb)
ON CONFLICT (id) DO UPDATE SET options = EXCLUDED.options;

-- +goose Down

DELETE FROM content WHERE component = 'process_arsenal';
DELETE FROM products WHERE slug = 'arkane';
