-- +goose Up

ALTER TABLE products ADD COLUMN IF NOT EXISTS slug TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS details JSONB NOT NULL DEFAULT '{}';

CREATE UNIQUE INDEX IF NOT EXISTS idx_products_slug ON products (slug);

INSERT INTO content (component, data) VALUES ('planets', '{"title": "Мы все сделаны из звёздной пыли","text": "Каждый атом в твоём теле — и в этом стуле, и в этой кружке — родился в раскалённом ядре давно угасшей звезды. Планеты собираются из межзвёздной пыли, гравитация лепит из неё миры, а мы просто пыль, которая научилась думать. Добро пожаловать домой."}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('hero', '{"badge": "О SPARROW","title": "Рождённый слой за слоем","subtitle": "Уникальные светильники из 3D-печати","cta_primary": {"text": "СМОТРЕТЬ МОДЕЛИ","link": "/catalog"},"cta_secondary": {"text": "КАК МЫ ДЕЛАЕМ","link": "/process"}}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('about', '{"label": "О SPARROW","title": "Свет как искусство","description": "Каждый светильник Sparrow — ручная работа. Никаких штампов, никаких повторов.","tags": ["Воробей — везде","Только 3D-печать","Любой цвет","PLA-пластик"]}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('about_hero', '{"label": "О SPARROW","title": "Мы вдохновляемся миром","description": "Sparrow — это больше чем светильники. Это философия. Гравитация притягивает всё к центру. Тени, свет, форма. Мы собираем всё в одно."}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('process_hero', '{"label": "Процесс","title": "От идеи до света","description": "Каждый этап — от рождения формы до появления теней — непосредственно в наших руках. Никакой фабричной фантазии."}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('process_stages', '{"stages":[{"title":"Форма","duration":"3–5 дней","description":"Модель рождается в 3D-пространстве. Мы наблюдаем, как тень меняет форму, как форма меняет тень.","color":"#ff4d00","icon_bg":"dark","tags":["3D-моделирование","Форма"]},{"title":"Печать","duration":"5–10 дней","description":"FDM-печать слоями. Градиентный переход цветов. Абажуры собираются как пазлы.","color":"#58cc02","icon_bg":"dark","tags":["FDM-печать","PLA"]},{"title":"Сборка","duration":"2–3 дня","description":"Сборка максимально бесшовно. Каждый шов — это где‑то там, где не должно быть шва.","color":"#7b61ff","icon_bg":"white","tags":["Сборка","Тщательно"]},{"title":"Ручная работа","duration":"3–5 дней","description":"Финишная обработка, удаление слоёв, полировка. Индивидуальная краска.","color":"#ff4d00","icon_bg":"dark","tags":["Финиш","Ручная работа"]},{"title":"Проверка","duration":"1 день","description":"Каждый светильник проверяется индивидуально. Цвет, яркость, стабильность.","color":"#58cc02","icon_bg":"dark","tags":["Тест","Качество"]},{"title":"Упаковка","duration":"1 день","description":"Фирменная упаковка с гравировкой. Внутри — инструкция и гарантийный талон.","color":"#7b61ff","icon_bg":"white","tags":["Упаковка","Фирменно"]}]}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('ticker', '{"items":["✦ 3D-ПЕЧАТЬ","✦ РУЧНАЯ РАБОТА","✦ УНИКАЛЬНЫЙ СВЕТ","✦ SPARROW","✦ ЖИВЫЕ ТЕНИ","✦ КАСТОМНЫЙ ЗАКАЗ","✦ ЭКОЛОГИЧНО","✦ СДЕЛАНО В РОССИИ"]}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('footer', '{"logo_text": "SPARROW","description": "3D-printed designer lamps. Каждый светильник — ручная работа.","social":[{"name": "Telegram","url": "#"},{"name": "VK","url": "#"},{"name": "WhatsApp","url": "#"}],"nav":[{"title": "Навигация","links":[{"text": "О нас","url": "/about"},{"text": "Модели","url": "/catalog"},{"text": "Процесс","url": "/process"},{"text": "Цифровые продукты","url": "/digital"},{"text": "Новости","url": "/blog"}]},{"title": "Контакты","links":[{"text": "hello@sparrow.studio","url": "mailto:hello@sparrow.studio"},{"text": "Москва, Россия","url": "#"}]},{"title": "Информация","links":[{"text": "Политика конфиденциальности","url": "/legal/privacy"},{"text": "Условия использования","url": "/legal/terms"}]}],"copyright": "© 2024 Sparrow"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('materials', '{"label": "МАТЕРИАЛЫ","title": "Из чего мы строим свет","materials":[{"name": "PLA","full_name": "Полимолочная кислота","description": "Биоразлагаемый, 14 цветов","color": "#00c45a","tags": ["Био","14 цв","Мат"]},{"name": "PETG","full_name": "Полиэтилентерефталат","description": "Прочный, полупрозрачный","color": "#7b61ff","tags": ["Прозр","Проч","8 цв"]},{"name": "ASA","full_name": "Акрилонитрил-стирол-акрилат","description": "УФ-стойкий, для улицы","color": "#ff4d00","tags": ["УФ","Влага","6 цв"]},{"name": "TPU","full_name": "Термопластичный полиуретан","description": "Гибкий, тактильный","color": "#ffd600","tags": ["Гибк","Мягк","Натур"]}]}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('reviews', '{"label": "ОТЗЫВЫ","title": "Говорят","rating": 4.9,"review_count": 143,"reviews":[{"id": 1,"name": "Алина К.","city": "Москва","text": "Тени на стенах потрясающие. Все гости спрашивают, где взяла.","color": "#ff4d00"},{"id": 2,"name": "Дмитрий Р.","city": "Санкт-Петербург","text": "Сделали под наш фирменный цвет — результат стоит того.","color": "#7b61ff"},{"id": 3,"name": "Маша Ю.","city": "Казань","text": "Идеальный подарок. Это по-настоящему уникально и не как у всех.","color": "#58cc02"},{"id": 4,"name": "Игорь С.","city": "Екатеринбург","text": "Хороший светильник, экологичный материал. Качеством доволен.","color": "#ffd600"}]}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('faq', '{"label": "FAQ","title": "Вопросы?","items":[{"question": "Сколько времени?","answer": "Среднее время изготовления — от 3 до 7 рабочих дней в зависимости от сложности модели."},{"question": "Нестандартный цвет?","answer": "Мы можем подобрать цвет по вашему образцу. Доступно более 50 оттенков PLA-пластика."},{"question": "Насколько прочные?","answer": "Светильники из PLA и PETG достаточно прочны для повседневного использования. ASA подходит для улицы."},{"question": "Доставка?","answer": "Отправляем по всей России СДЭКом и Почтой России. Стоимость зависит от региона."},{"question": "Гарантия?","answer": "Мы даём гарантию 6 месяцев на все светильники. При производственном браке заменим изделие."},{"question": "Какая лампочка?","answer": "Подходит стандартная лампочка с цоколем E27. Рекомендуем LED-лампы — они не нагревают пластик."}]}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('product_hero_section', '{"price_label": "Ориентировочная стоимость","buttons": {"order": "ОФОРМИТЬ ПРЕДЗАКАЗ","similar": "СДЕЛАТЬ ПОХОЖИЙ"},"loading": "Загрузка...","not_found": "Товар не найден"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('product_specs_section', '{"badge": "ХАРАКТЕРИСТИКИ","heading": "Технические данные"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('product_box_section', '{"badge": "КОМПЛЕКТАЦИЯ","heading": "В коробке"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('product_story_section', '{"badge": "ОБ ИЗДЕЛИИ","heading": "История модели"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('digital_features_section', '{"badge": "ВОЗМОЖНОСТИ"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('digital_architecture_section', '{"badge": "КАК ЭТО РАБОТАЕТ","heading": "Архитектура системы"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('digital_techstack_section', '{"badge": "ТЕХНОЛОГИИ","heading": "Стек"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('digital_opensource_section', '{"heading": "Открытый код","button_text": "НА GITHUB"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('navigation', '[{"id": "about", "title": "About", "to": "/about", "icon": "about"},{"id": "catalog", "title": "Catalog", "to": "/catalog", "icon": "catalog"},{"id": "process", "title": "Process", "to": "/process", "icon": "process"},{"id": "digital-catalog", "title": "Digital Catalog", "to": "/digital-catalog", "icon": "digital-catalog"},{"id": "constructor", "title": "Constructor", "to": "/constructor", "icon": "constructor"}]') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('catalog_page', '{"breadcrumbs": [{"label": "Главная", "to": "/"},{"label": "Каталог", "to": "/catalog"}],"page_title": "Каталог","empty_state": "Нет товаров в этой категории"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('catalog_cta', '{"heading": "Твой свет уже ждёт","description": "Оставь заявку — обсудим размер, цвет и материал. Первая консультация бесплатно.","button_text": "Создать свой"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('product_page', '{"sections": {"specs": {"badge": "ХАРАКТЕРИСТИКИ", "heading": "Технические данные"},"box": {"badge": "КОМПЛЕКТАЦИЯ", "heading": "В коробке"},"story": {"badge": "ОБ ИЗДЕЛИИ", "heading": "История модели"}},"price_label": "Ориентировочная стоимость","buttons": {"order": "ОФОРМИТЬ ПРЕДЗАКАЗ","similar": "СДЕЛАТЬ ПОХОЖИЙ"},"not_found": "Товар не найден","loading": "Загрузка..."}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('digital_catalog_page', '{"breadcrumbs": [{"label": "Главная", "to": "/"},{"label": "Цифровые продукты", "to": "/digital-catalog"}],"hero": {"badge": "ЦИФРОВЫЕ ПРОДУКТЫ","heading": "Open-source инфраструктура","description": "Sparrow разрабатывает не только светильники. Наши цифровые продукты — открытые, модульные и готовые к использованию."},"button_text": "ПОДРОБНЕЕ →"}') ON CONFLICT (component) DO NOTHING;
INSERT INTO content (component, data) VALUES ('digital_product_page', '{"features_label": "ВОЗМОЖНОСТИ","not_found": "Product not found","loading": "Загрузка..."}') ON CONFLICT (component) DO NOTHING;

INSERT INTO categories (name, slug) VALUES ('Все', 'all') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug) VALUES ('Светильники', 'lamps') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug) VALUES ('Ночники', 'nightlights') ON CONFLICT (slug) DO NOTHING;

INSERT INTO products (name, name_ru, price, badge, colors, bg_color, category_id, in_stock, slug, details) VALUES ('Nido', 'Гнездо', 4900, 'ХИТ', '["#c84b00","#1a1a2e","#f5f0e8"]', '#fff0eb', 2, false, 'nido', '{}') ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (name, name_ru, price, badge, colors, bg_color, category_id, in_stock, slug, details) VALUES ('Flock', 'Стая', 7800, 'ПРЕМИУМ', '["#ff4d00","#ffd600","#58cc02"]', '#f0edff', 2, false, 'flock', '{}') ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (name, name_ru, price, badge, colors, bg_color, category_id, in_stock, slug, details) VALUES ('Nido', 'Гнездо', 4900, 'ХИТ', '["#c84b00","#1a1a2e","#f5f0e8"]', '#fff0eb', 3, false, 'nido-night', '{}') ON CONFLICT (slug) DO NOTHING;
INSERT INTO products (name, name_ru, price, badge, colors, bg_color, category_id, in_stock, slug, details) VALUES ('Flock', 'Стая', 7800, 'ПРЕМИУМ', '["#ff4d00","#ffd600","#58cc02"]', '#f0edff', 3, false, 'flock-night', '{}') ON CONFLICT (slug) DO NOTHING;

INSERT INTO digital_products (slug, number, title, subtitle, description, content) VALUES ('air', 1, 'AIR', 'Облачная платформа умного освещения', 'Собственная облачная инфраструктура Sparrow для управления светильниками, сбора аналитики и интеграции с умным домом. Микросервисная архитектура на базе MQTT, WebSocket и JWT.', '{}') ON CONFLICT (slug) DO NOTHING;
INSERT INTO digital_products (slug, number, title, subtitle, description, content) VALUES ('account', 2, 'ACCOUNT', 'Сервис аккаунтов и авторизации', 'Самостоятельный AGPL-3.0 сервис аккаунтов, авторизации и профилей. HTTP API, gRPC, Vue SPA, OpenAPI и Swagger UI. Готов к развёртыванию в Docker Compose или Kubernetes.', '{}') ON CONFLICT (slug) DO NOTHING;

INSERT INTO configurator_options (options) VALUES ('{}');

-- +goose Down
DELETE FROM configurator_options;
DELETE FROM digital_products;
DELETE FROM products;
DELETE FROM categories;
DELETE FROM content;

DROP INDEX IF EXISTS idx_products_slug;
ALTER TABLE products DROP COLUMN IF EXISTS slug;
ALTER TABLE products DROP COLUMN IF EXISTS details;
